### ISSUE TITLE
Feature request: Show both real name *and* email address

### ISSUE THREAD

**Issue by mburnicki** [thundernest/k-9#1119]
In the current version you can only configure ti show either a correpondent's real name **or** his email address.
https://github.com/k9mail/k-9/wiki/Manual-GlobalSettings#show-correspondent-names

Many of my contacts use different email addresses. If they write from an email address which is not yet stored in the contact information then a saved contact can't be assigned and displayed, so it would be good to see the email address, and add it to the saved contact. Unless the email address is somehow related to the real name it's not easy to see who has sent the email.

On the other hand, I've recently received a couple of emails with a well-known real name, but a faked email address, If I only see the real name of an email containing a link to a web page I could easily assume this has been sent by a known person, and click on that link. However, if I can see the email address which is obviously not related to real name I can easily identify the email as phishing or spam.

So I'd really prefer to see both the real name **and** email address in the email list view as well as when the individual email is displayed.

**Comment by cketti** [comment]
I don't want to add support for showing both name and email address in the message list. That's way too much text and not very pretty. Another setting would also needlessly increase the code complexity.

However, in the message view I'd like to be able to see the full recipient information, too. But I like the "View details" approach of the Gmail app better than the idea of adding another setting.

**Comment by xoxys** [comment]
In times of mail sender spoofing I would really like to see the sender name and the email as this would help a lot ro identify fake senser names before someone opens a mail...

**Comment by PhoenixIV** [comment]
I was about to request an "extend header" button when I saw this request. This is what I thought:
![photo_2021-11-07_23-09-30](https://user-images.githubusercontent.com/2091755/140663703-732a75eb-1368-40ae-a28d-32afc161bd48.jpg)

Right now I have to go into the technical headers text file view from the three-dot-menu. Not good.

**Comment by ashegoulding** [comment]
> I don't want to add support for showing both name and email address in the message list. That's way too much text and not very pretty. Another setting would also needlessly increase the code complexity.
> 
> However, in the message view I'd like to be able to see the full recipient information, too. But I like the "View details" approach of the Gmail app better than the idea of adding another setting.

YOU don't want to despite the fact that this many people saw this most basic feature necessary just because you don't find it pretty? So you're not going to accept any pull req for this?
I mean, I've set up all my accounts and everything using K-9 and it's kinda disappointing to see ref flags like this one after another. I'm tired of looking at the mail headers to figure out how the mails got to my accounts.

**Comment by StefanBertels** [comment]
While I really miss this feature, too -- I don't think grumbling will help.
This is a voluntary maintained OSS, so let's be kind and motivate @cketti, e.g. by [sponsoring](https://cketti.de/sponsor/). :-)

**Comment by babanga** [comment]
You are absolutely right, I'm very sorry. But it's not just a feature, but essential feature. It's like a bookmarks manager, where you can see only the titles OR the links, and there's no option to hover it, only to check the pages source code. I was looking for an email client, and there are not that many real ones, most are just "services" that saves your credentials & emails on their servers and provides you with the ui. Every review I saw described k9 as "dated, oldscool & classic, the one you dad used to". That's what I'm looking for (I thought)! I've set it up, moved there all the emails and then found out there's no such basic option as seeing the senders address.
(sorry for atrocious english)

**Comment by binki** [comment]
I think only seeing the name and trusting the sender-set name by default is a security issue. By trying to be too friendly, the default settings make it impossible for one to distinguish between a legitimate sender and an imposter who has an obviously spammy email address.

I think the option of only showing the email is better/safer, so I have switched to that. If I want to see the sender-specified name, I can always look in the headers. I wan to do that seldom enough that the inconvenience is tolerable.

Could the default value be changed?

**Comment by PhoenixIV** [comment]
! Disclaimer: This post is off-topic

> Every review I saw described k9 as "dated, oldscool & classic, the one you dad used to". That's what I'm looking for (I thought)!

Based on your description I can recommend https://github.com/M66B/FairEmail 
I switched from FairEmail to K-9 because K-9 had a way more modern / sleek design, based on my opinion.

**Comment by babanga** [comment]
Oh, thanks, I've tried fairmail, but wasn't even able to complete the initial setup, it's just too messy. It's great that it's so much feature rich but it looks more like a debugging tool rather than an email client.
I would like to have a simple email client, that looks like.. an email client, not a fancy messenger. Like they used to, gmail <2019 for example, but with ability to check the source (headers). And that shows the sender email and the CC emails as well.

**Comment by ashegoulding** [comment]
I'd gladly implement this missing feature, but I stopped when I saw the bit "not pretty". I guess this is just a downside of FOSS projects. But seriously though, we could see the mentality behind this project. They think that this is the project of their own. Time to fork or abandon ship.

**Comment by IBBoard** [comment]
I've just found out about (or possibly rediscovered) the "Show correspondent names" setting. Personally, I'd be if disabling "Show correspondent names" still allowed "Show contact names" so that I get the human readable names for people in my contact list but email addresses (rather than the name that they choose) for unknown third-parties. It feels like a compromise between trying to show both, and only having "show email" or "show (potentially fake) display name".

**Comment by umlaeute** [comment]
i think myself as pretty security aware.

but recently I almost fell for a fraudster simply because the email-address is not shown.
(it was one of those "There was some unusual activity with your GitHub token" phishing mails).

so i turned off the "Show correspondent names" options.

Now, whenever someone comments on GitHub on one of my many tickets, I get an email from `notifications@github.com`, with absolutely¹ no indication on *who* commented. (which makes the mail a little bit useless, as I cannot properly contextualize the comment).
Looking at 2.5 pages of headers to find (hopefully) find the `From:` line, is not really helpful here.

i understand the concerns about keeping a clean interface, but i would very much welcome a quick way to *fully* inspect the from/to/cc/bcc list

**Comment by konradmoesch** [comment]
Is this really a 6y old issue for such a small feature that all other mail clients I know have?
I'm really disappointed..

As many of you said before, for me it's very important to see both the name and the address of a sender in the message view for security, but also usability reasons.

Please implement such a small feature!
You could also leave the default to "Name only", if you feel more comfortable with the "simplicity" of the interface..
But I think there are many options to support showing both values in a "pretty" way (I mean Thunderbird etc have solved it):
* Name <Address>
* Address on a separate line (maybe even smaller font) below name
* Some kind of dot/arrow menu to show "more details"
Does anybody have a better option I did not come up with?

I'd hope to see the address and name quickly with not many klicks, but imo everything can only be better to the current scrolling through headers workaround

**Comment by binki** [comment]
> I'd hope to see the address and name quickly with not many klicks, but imo everything can only be better to the current scrolling through headers workaround

Using the existing setting to show only the email isn’t too bad. It’s reminiscent of the AIM days where you would memorize your friends’ screen names. Those were the days!

**Comment by mimi89999** [comment]
I think that at least taping on the sender name in the message view should show his email address and not just suggest adding him to contacts.

**Comment by vinaypai** [comment]
As other people have pointed out, this should be treated as a security issue because it makes phishing way too easy.  I see that a complete fix may come with the message view redesign #6198. But maybe a quick improvement would be to at least change the click behavior.

Clicking a name just shows "Add to contacts" with Cancel/Ok actions.  That could be changed to something like "Add Jon Smith <phisher@definitely.not.john.smith.com> to contacts?.  This simple text change will at least get us part way there.

**Comment by cketti** [comment]
The message details screen available since K-9 Mail 6.505 (beta) shows both the display name and email address for all sender and recipient headers. Closing this issue.

**Comment by kenbyte** [comment]
It's more than two years later and this still hasn't made it to stable. When should we expect that to happen?

**Comment by umlaeute** [comment]
@kenbyte while i haven't checked myself yet i see:
- a fix was apparently committed *2 months* ago (don't know where you got the "*2 years*" from)
- this fix made it into k-9 v6.505
- k-9 v6.600 was released 5 days ago
- i assume that v6.600 will include fixes from v6.505

**Comment by kenbyte** [comment]
I apologize — I misread the date on one of the messages. Just got the update; thanks for making such an incredible and amazing app!! I hope you have an excellent day.

**Comment by ccpf** [comment]
HTML (including in signatures) was implemented in the K@-mail fork about 8 years ago. I understand that it is a volunteer run project, but I am not sure what is taking so long in K9-mail. Couldn't you have just included what the K@-mail guys did? Especially as it is set to be the Thunderbird for Android, HTML simply is a MUST in 2023. While HTML may not be an absolute requirement for private emails, show me a business email without a logo or some other formatting in the signature these days. And if I need a separate mail client to send my business emails, I might as well use the same client for my private ones as well, essentially rendering K9 superfluous. So please, make this a priority.

**Comment by Vrihub** [comment]
I can't believe this is still a bug. Every email program I ever used has this feature!

Please add an option to have BOTH the sender name and email address visible, BOTH in the messages list view and in the individual message view.

One should be able to always see both in every situation without having to click on anything. 

Please let the user choose between a "clean" (incomplete) interface or a richer one.

**Comment by jondaley** [comment]
Just got tricked by a scammer due to this bug. 

I can't click on the name of every single sender and displaying only the email address is annoying. 

It can't really be "lots of code" to simply display
   Mr. Smith <joe@smith.com>

can it?

**Comment by dxdxdt** [comment]
Damn. Still didn't implement this thing. Just complete utter incompetence.

Fun fact: the original maintainer who rejected this feature [left](https://cketti.de/2025/02/26/goodbye-k9mail/). Good riddance. Perhaps we can start discussing why it is essential once again. It's frustrating when opensource devs just ignores the patches submitted on a silver platter just because it's against their own biases. What a view, mate.
