### ISSUE TITLE
Long-press on e-mail address -> menu (copy address / new e-mail)

### ISSUE THREAD

**Issue by spectas** [thundernest/k-9#1242]
When you want to work on with an e-mail address (sender, CC, BCC), it is quite difficult to extract the address first. For example you want to forward somebody the sender's e-mail address ("Can you send me the address of ...?") or create a new (clean) mail to the guy with the CC address.

It would be great, to be able to open a small menu after a long-press on an e-mail address. The menu should contain the items: 1. "Add to contacts" (or "Open contact" when already added to contacts), 2. "Copy to clipobard", 3. "Start new e-mail" (to this address). This behaviour is known for example from the AOSP contact app. A long-press on an address asks you to copy to clipboard, too.

There is workaround I use, but it is rather complicated: options menu of an e-mail, "Show headers" and then you can copy parts of the mail header like normal text.

Sincerely
Spectas

PS: I played a bit with Gimp to show a bit, how this could look like:
![k9-screenshot3](https://cloud.githubusercontent.com/assets/3306424/14177844/8015d30a-f758-11e5-9fde-842b833f839f.png)

**Comment by philipwhiuk** [comment]
There's been lots of suggestions in this area. It all boils down to the same thing - what we have is not intuitive / consistent / feature complete.

See #1120 #1070 

I think we want to design it properly. I'm going to leave this open, but we should consider it as part of a design overhaul rather than making changes when tapping on a specific bit.

**Comment by cketti** [comment]
Closing this in favor of #6181.
