### ISSUE TITLE
Implement the DIME protocol

### ISSUE THREAD

**Issue by yoshimo** [thundernest/k-9#2139]
Lavabit.com has reopened their business and is back with a new e-mail protocol that protects metadata and gives encryption from the get go. 
To really protect the user this needs to be done on the users client.
I therefore would like to see an implementation of https://darkmail.info/spec in k9 eventually

**Comment by cketti** [comment]
It's a pretty radical change from the current way we do email. Maybe too radical. Due to that I don't see this being widely adopted.
But maybe someone has a lot of free time on their hands and wants to take a stab at an implementation. It probably requires quite a few changes to K-9 Mail. So be prepared to write the code twice. Once as prototype to figure out what changes are necessary and then another time to do it properly and get it integrated into our K-9 Mail.

**Comment by philipwhiuk** [comment]
The following will have to be done:

* An implementation of a DIME message builder. My guess is this is some combination of reusing the existing MessageBuilder only more extensively rewritten
* An implementation of DMAP. This is at current impossible because, as long as it is, that spec doesn't cover DMAP. This alone is going to be closely equivalent to writing a copy of the ImapStore I expect. One hopes lots of common code re-use.
* An implementation of DMTP. Again, maybe lots of common ground with SMTP but lots of new 'signet' related code.

Amongst all this is sub-requirements, like DNSSEC ( #1776 ) support and some kind of global ledger and lots of other as yet unspecified content.

**Comment by cketti** [comment]
I think by now it's safe to say that DIME is unlikely to be picked up by the wider internet anytime soon.
