### ISSUE TITLE
Support swiping between messages in message view

### ISSUE THREAD

**Issue by mruwek** [thundernest/k-9#585]
Current "gesture navigation" in K9 is just fiction. On the other hand implementation in quite a few open source apps (including AOSP E-mail app) looks as good as in Gmail, so maybe we too can have this feature _properly_ done in near future?

**Comment by jancborchardt** [comment]
Yes, it’d really be cool to have that. Maybe something to be done as part of the Material design update https://github.com/k9mail/k-9/issues/599?

**Comment by uudruid74** [comment]
How do I assign myself to this?  I'm gonna take a look this weekend and try to get the basics going.  My goal is swipe left/right to change messages, down for "download rest of message", double-tap for reply (need to indicate if default is Reply, Reply All, or Menu), and long-press for trash/spam/archive/folder options.  Reasonable?

**Comment by uudruid74** [comment]
Changed mind on Long-press since this interferes with text selection.  And the new interface is a bit more sane and usable than the one I was originally using.  I haven't messed with Android in a long time so reading the code took me forever.  The next/prev and double-tap to reply were all of about 6 lines total.   There is some other stuff I'm not done implementing and it looks really bad without animations, but it works OK.  Should I do a pull request? Or wait until the half implemented stuff is working (it may be awhile before I get to it).

**Comment by jancborchardt** [comment]
@uudruid74 awesome! :) I don’t know how development is handled here specifically, but at ownCloud we do pull requests as early as possible so folks can already see if it’s going into the right direction and give feedback early.

**Comment by cketti** [comment]
We already had support for simple swipe gestures to move to the previous or next message. But we disabled them because doing it the 'easy' way leads to a poor user experience. The easy way was detecting gestures and then performing the action, without any kind of visual feedback.

Issues with the simple approach that I can remember:
* interferes with horizontal scrolling in WebView
* limiting to bezel swipes makes for an odd user experience when split view is enabled
* functionality is not easy to discover

For a user-friendly swipe mechanism visual feedback is absolutely necessary. See e.g. the Gmail app.
I'm not a fan of including any other gestures in the message view screen, especially since we have a WebView that can potentially scroll in every direction.

To implement proper swiping between messages we need some kind of view pager. The code is already somewhat prepared for this in that we don't reuse `MessageViewFragment` instances but create a new instance per message we want to display. That way it shouldn't be too hard to introduce a `ViewPager`. Additional code is needed to only enable swiping to the previous/next message once the `WebView` is scrolled all the way to the left/right.
I haven't looked at the AOSP Email source to check if we can simply copy their implementation.

**Comment by uudruid74** [comment]
Yes, it did look like support was already there.  It was too easy.  However, the version I downloaded had a bunch of bin descript icons at the bottom and I think I deleted about 3 messages accidently looking for Reply.   I finally had to look it up unline.  Hit extension menu, then Send, then Reply.   So ... the argument that gestures aren't easy to discover is really lost.  Worst UI I ever used.

So, I came into this because I had to do something to get the features I use more accessible.  But it wasn't until I got the latest git that I saw much of this was fixed.  I will look into the animations and detecting scrolling of Webview.   If people think gestures are a bad user experience, there is a button to turn them off, right?

**Comment by EasyBrowser** [comment]
I'm just moving to K9 from the Samsung Galaxy S5 native app and quite like the native app's simple swipe gestures to move to the previous or next message and would like to see it in K9 as well if possible.

**Comment by SamuelWitke** [comment]
Is this issue still open, I believe it could be solve by implementing a viewpager, or nav menu.

**Comment by bvn13** [comment]
+1
really need gestures in mail list to delete mail.

**Comment by traumschule** [comment]
Please do it!
