### ISSUE TITLE
OAuth2 support for POP3 (receiving email)

### ISSUE THREAD

**Issue by bitshftr** [thundernest/k-9#6216]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

My Office365 mail (corporate) requires OAuth2 for the "Authentication" setting.  This would be on the "Incoming server settings" screen.  I see that OAuth2 was added for SMTP authentication, which is great...I will be able to send emails, but I can't receive emails from the outlook.office365.com POP3 server yet.

### Suggested solution

Please add OAuth2 on the POP3 server settings screen.

**Comment by cketti** [comment]
Please use IMAP instead. See #4974.

**Comment by bitshftr** [comment]
IMAP doesn't work for my process/workflow.  I use POP3 for my work email on my personal phone, but only when I'm traveling, which is rarely.  Other than traveling, I don't check my work email on my personal phone.  I don't want to use IMAP or sync all of my email onto my phone.  I only want to receive on my phone those messages that have come in since I left the office.  I do not want those messages removed from the server, or even marked as "read" on the server.

**Comment by mavoga** [comment]
I really wonder how the admin of my Company did set up my Office 365 mailbox, but I'm unable to use IMAP and I only get this:

`Unable to connect to server. (Command: NAMESPACE; response: #4# [BAD, User is authenticated but not connected.])`

Even Thunderbird can't access my mailbox via IMAP, but it can happily access it via POP3 with Oauth2: this makes me believe my problem is due to the configuration of the mailbox which simply has IMAP access disabled (and I can't find any switch to enable it).

All these troubles could be solved if Oauth2 auth method was available on POP3 too... please enable such auth method, I suppose all the needed code is already there!
