### ISSUE TITLE
Message re-design proposal

### ISSUE THREAD

**Issue by carmarri** [thundernest/k-9#6530]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.4.0

### Problem you are trying to solve

According to the new message design shown in https://blog.thunderbird.net/2022/12/thunderbird-for-android-preview-modern-message-redesign/

I think there are two many colours, buttons and boxes. It does feel that the structure and design is not consistent.

Also discussing with a colleague we think that it would be good to have a different design or structure, so I hope these suggestions could be useful.

### Suggested solution

I would like to propose a radical different approach for the layout, based on bubbles to resemble to an instant messaging app. This is a conversation-oriented structure to make things clearer (maybe a too radical/risky design).

A bubble contains the the subject, pointing to the person who created the message, since it is more visual and easier to identify.
And I think that icons to "Respond" and "Favourite" should be inside the bubble, since it refer to the message, no to the person.

### Screenshots / Drawings / Technical details

This is a proposal for the message window, when a conversation appears and the messages are folded:
![thunderbird_android_folded](https://user-images.githubusercontent.com/16718279/207299082-3d8f4b13-fa75-4a09-b80c-05cfbe8b96b1.png)

Here is the same window but with the messages unfolded:
![thunderbird_android_conversation_unfolded](https://user-images.githubusercontent.com/16718279/207299094-3bccd145-c04d-40b7-95ce-14f10353cfa8.png)

**Comment by cketti** [comment]
Thank you for sharing your design. But this is a radical change from both what we have now and how email clients typically display messages/conversations. Most people don't use email like an instant messenger. So we're currently not looking to add such a chat mode (but there is a feature request for it, see #1887).

I'm closing this issue because it doesn't make sense for us to keep track of this design proposal separately. By mentioning the feature request #1887, a link to this issue will be automatically included in the feature request's timeline. So if we ever decide to implement a chat mode, we can revisit this design.

If you're interested in using email like an instant messenger, you might want to check out [Delta Chat](https://delta.chat/).
