### ISSUE TITLE
Message view metadata too simplified, previous display requested back

### ISSUE THREAD

**Issue by oh2kku** [thundernest/k-9#6631]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.506

### Problem you are trying to solve

Update within the last few versions of K9 has dumbed down the message metadata display in message view screen. It does not show the sender email address (if there is a name) anymore, time is abstracted to just "Sun" etc weekday name if it's not from the current day. To see the details I have to click the field to get a popup. Also whether my email address is actually in the to or cc field is not known until I open the popup and look there.

This hurts usability. Please return the old behavior or at least make it configurable with a setting. I tried to look for a setting to return the old behavior, but did not find one.

### Suggested solution

See above

### Screenshots / Drawings / Technical details

Receiver email address intentionally garbled. Currently observed unwanted message read view:

![Screenshot_20230206-154705](https://user-images.githubusercontent.com/2458254/216988795-080a8143-d4f8-4f8d-a7c3-ea1997cdfa07.jpg)

**Comment by cketti** [comment]
It only hurts usability if the sender/recipient information or the exact date is more important than the actual message content. For most people, that's not the case.

If you are interested in message details, the new screen provides more information than the old view did. And it allows to add even more details in the future without overloading the message view screen.

We have no plans of maintaining two separate UIs and providing a setting to switch back to the old behavior.

You can still show email addresses instead of display names by changing *Settings → General settings → Display → Show correspondent names*.

**Comment by oh2kku** [comment]
At least consider adding the time of the message to messages that arrived yesterday or before, there is plenty of room in the UI. Instead of just "Sun", it could say "Sun 14:58"

  Tapio
