### ISSUE TITLE
improve the visibility of unread messages when using dark theme

### ISSUE THREAD

**Issue by vagner-dias** [thundernest/k-9#6692]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.400

### Problem you are trying to solve

The visibility and identification of unread messages using the dark theme is difficult, so I suggest to improve it perhaps by changing the color of read messages to gray

Here is a screenshot to demonstrate - this was taken on a OnePlus 6

Congratulations for the The team for this awesome app!

![Screenshot_20230221-075643](https://user-images.githubusercontent.com/86367839/220326341-0be605ac-597c-48c7-9535-3270b8f13e48.jpg)

### Suggested solution

Change the color of read messages to gray - here is a screenshot of the nine app which seems to be doing that

![Screenshot_20230221-080208](https://user-images.githubusercontent.com/86367839/220327661-c919457e-90a0-4f2e-8579-116d17da6ca7.jpg)

**Comment by vimpostor** [comment]
I still think that after #6693 the difference between read/unread is not clear enough.
I can't tell from a quick glance where unread messages end and where read messages are. It's only clear if I focus my eyes at single messages, which is really not how a mail client should work.

Is there any way this could improved further? Take a look at GMail for example, there I can tell immediately where the unread mails are, because the text is not only bold but also in a slightly larger font size and with a clearer color contrast.

Another example is Outlook where you can also clearly separate the two, because unread messages are colored in blue.

I usually don't have any problems with stuff like this, I can only imagine how hard this must be for people with accessibility requirements.

**Comment by cketti** [comment]
K-9 Mail allows you to change the font size of the various pieces of information in the message list, see https://docs.k9mail.app/en/6.400/settings/general/#font-size

The app also supports changing the background color of message list items when a message is (un)read, see https://docs.k9mail.app/en/6.400/settings/general/#change-colour-when-read

**Comment by vimpostor** [comment]
Oh wow, thanks for pointing me in the right direction, I didn't know about this.

Now having configured it to show them in a different color, it works perfectly. :)
