### ISSUE TITLE
Fix 6.601 UI

### ISSUE THREAD

**Issue by lifebarier** [thundernest/k-9#6834]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.601

### Problem you are trying to solve

Even more UI functionality is lost with new redesign

### Suggested solution

Rework message view:

0. FULL DATE! Use full date in message view. Message list too.  'Sat' tells me nothing. (You already forced us to click more with rework of multiple accounts support in previous updates, now we need to click more in message view? Good job)
1. Decrease padding around sender details - It is already of different color so no need to separate it more. Padding around 'show remote images' is not needed (esp between receiver and button).
2. 'to me' should print full email this was sent to - it hides exact email that was used to send this message ( "+" in email hack ) 
3. Just remove that pill with account name and use color coding bar again.
4. Fire whoever is designing this.

What is with constant reworks to waste more and more screen space and show less and less information?

**Comment by cketti** [comment]
0. The full date and time is available in the new message details screen.
2. "to me" is only displayed if the account has just one identity. If the account has multiple identities the name of the identity will be displayed instead of "me".

Offering the most dense layout possible is not a design goal for K-9 Mail. If you prefer a more information-dense layout, maybe [FairEmail](https://email.faircode.eu/) is a better fit for you.
