### ISSUE TITLE
First launch: cannot bypass the email address setup screen, cannot get to the main screen and go to settings!

### ISSUE THREAD

**Issue by A-7666** [thundernest/k-9#6859]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.601

### Problem you are trying to solve

I installed K-9, launched it, and saw the screen to enter email address, and 2 buttons (manual setup and next).
Unfortunately I could not bypass this and get to the main screen.

This is a strange behavior.
I've used several mail clients on desktop, FairMail on the phone, and they all let me access the main screen without any mailboxes added, so I can go to settings/options and configure the program the way I want, before connecting it to any mailboxes. This is the way I always go with any software - first configure, and then start using.
And it's weird and sad that this cannot be done on K-9, and the user has no choice other than adding a mailbox or exit.

I would like to ask to fix this and make K-9 open the main screen on the first launch,
instead of forcing the user to set up a mailbox without any way to bypass it.

### Suggested solution

Make K-9 open the main screen on the first launch, instead of forcing the user to set up a mailbox without any way to bypass it.

**Comment by cketti** [comment]
Allowing the user to view the message list screen without having an account configured doesn't make any sense. There's nothing to do. And we'd have to spend extra work to make sure the app doesn't crash because many places assume there's at least one account.

It might make sense to expose a handful of settings when there's no accounts and the main UI isn't accessible. Things like the app language or the app theme. However, most settings don't make sense until the user has an idea of what the UI/UX looks/feels like with actual account/message data.

**Comment by A-7666** [comment]
>> to view the message list
Not the message list but the main screen from where settings, "about" and other stuff can be opened from the menu.
(or is it the same thing? if yes then to the empty message screen)

>> doesn't make any sense
It does make sense, a lot of sense.
Check Thunderbird or other client (desktop), check FairMail (mobile/AOSP).

Forcing the user is not ok.
Kindly give the user a choice to skip adding new mailbox and move forward to the main screen.

**Comment by ByteHamster** [comment]
> Not the message list but the main screen from where settings, "about" and other stuff can be opened from the menu.

Huh, you didn't even try using K-9 before writing a feature request?

> Kindly give the user a choice to skip adding new mailbox and move forward to the main screen.

Why do you need this? Not "because other apps do it", but what exactly were you trying to do? Why should K-9 not add new features and instead spend the limited development time on a "fake" empty email account screen when there is no account yet? Why should K-9 spend time on testing and maintaining this empty screen instead of testing and maintaining actual email functionality?

**Comment by A-7666** [comment]
Ok got it.
Sticking with FairMail.
