### ISSUE TITLE
Emails no longer display time sent/received - pls restore

### ISSUE THREAD

**Issue by Dave-Rado** [thundernest/k-9#6901]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.601

### Problem you are trying to solve

My emails used to display the date and time sent or received. Now they only display the date, unless it was sent or received today, in which case it only displays the time. So I am now having to use a different email client simply in order to find out what time an email was sent or received, which is crazy. 

### Suggested solution

Please could you restore the ability for k-9 mail to display the date AND time that emails were sent or received.

**Comment by cketti** [comment]
Tap the message header (gray background) to open a detail view containing the full date and time.

<img src="https://github.com/thundernest/k-9/assets/218061/e2cef01e-3ab7-46a5-a4db-cd1abe224220" alt="image" width=300>

**Comment by Vrihub** [comment]
Having to open each message and tap on its header is not a solution!

Please provide a configuration option to display full date and time both in the messages list view and in the single message view, so that the user can see the full timestamp in both views at a glance, without any further action required.

Every decent email client has this feature.
