### ISSUE TITLE
Why K-9/Thunderbird uses Weblate?

### ISSUE THREAD

**Issue by kazushi3** [thundernest/k-9#7275]
Hi,
I'm Japanese translator. 
Mozilla has [Pontoon](pontoon.mozilla.org) and Thunderbird for Desktop are translated in it. I think Pontoon has better Translation Memory about Thunderbird. Why K-9/Thunderbird use Weblate? Do you have any plans to use Pontoon?
Thanks.

**Comment by cketti** [comment]
For most of its existence K-9 Mail hasn't been part of Mozilla. So people who translated K-9 Mail in the past (and still do so today) are mostly not familiar with Pantoon. Many of them, however, translate other Android open source projects. Many of those projects use Weblate. So more than one translator asked us to switch to Weblate because that's what they're most familiar with.

We have no plans to use Pontoon.
